load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "lib_message",
    srcs = [
        "hello.go",
    ],
    importpath = "github.com/kaito2/bazel-practice/stage2/lib/message",
    visibility = ["//visibility:public"]
    # visibility = ["//app/cmd:__pkg__"],
)
